### ISSUE TITLE
Add a Scala 2.13.0-M3 build

### ISSUE THREAD

**Issue by LukaJCB** [typelevel/machinist#22]

**Comment by SethTisue** [comment]
machinist is already compiling fine in the Scala 2.13 community build, with tests passing, so very likely this is just a matter of pulling the usual levers

**Comment by xuwei-k** [comment]
https://repo1.maven.org/maven2/org/typelevel/machinist_2.13.0-M3/

**Comment by SethTisue** [comment]
looks like this issue can be closed, then?
