### ISSUE TITLE
publish for Scala 2.13.0-M5?

### ISSUE THREAD

**Issue by SethTisue** [typelevel/machinist#31]
will be needed before cats can publish, I think

**Comment by erikerlandson** [comment]
also needed for https://github.com/non/spire/issues/742

**Comment by larsrh** [comment]
I'm sorry, I accidentally wasn't subscribed to this repository. I'm working on it.

**Comment by larsrh** [comment]
#32 is merged. I'm running the release now.

**Comment by larsrh** [comment]
0.6.6 out.
