### ISSUE TITLE
Question: Does this make working with MonadTransformers "free"? 

### ISSUE THREAD

**Issue by AesaKamar** [typelevel/machinist#43]
From my understanding, the biggest cost associated with using a MonadTransformer stack in Scala is the constant need to box and unbox values for enrichment and calling typeclass methods. 

Is my understanding incorrect in thinking that this project solves a lot of those problems?

**Comment by larsrh** [comment]
Hi Aesa, for general questions, please refer to our Gitter channel: https://gitter.im/typelevel/general
